[build]
  command = "npm run build"
  base = "Grocery_Menu_Frontend/"
  [context.deploy-preview]

  publish = "Grocery_Menu_Frontend/build/"

  [[redirects]]
  from = "/"
  to = "https://5ef379b7994fee6c2cb9b34f--elastic-jepsen-79d118.netlify.app/"